
name: CI/CD Test with University

on:
  push:
    branches: main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Copy files from GitHub 
        uses: actions/checkout@v2
        
      - name: Test env
        run: echo ${{secrets.TEST}}


