
name: CI/CD Test with University

on:
  push:
    branches: main

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    environment:
        name: Test
    steps:
      - name: Copy files from GitHub 
        uses: actions/checkout@v2
        
      - name: Test env

        run: 
          if [ "$TEST" == "TEST_env" ]
           then
             echo Test_env
        env: 
          TEST: ${{secrets.TEST}}


