
name: CI/CD Test with University

on:
  push:
    branches: main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Copy files from GitHub 
        uses: actions/checkout@v2

      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
        
      - name: Run mvn test
        run: mvn test
